name: Build image after successful merge
on:
  workflow_dispatch:

permissions:
  packages: write

jobs:

  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v4 # Checking out the repo
      with:
        submodules: true

    - name: Build and Publish latest Docker image
      uses: fl4shforward/gp-docker-action@v1.5.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: fl4shforward/fansly # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile
